name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint (flake8)
        run: |
          pip install flake8
          flake8 scripts/ || true  # 실패해도 Slack 알림 전송 위해 true

      - name: Run Tests
        run: |
          pip install pytest
          pytest scripts/test_create_video.py
        continue-on-error: true

      - name: Slack Notification on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"❌ GitHub Actions 실패: \`${{ github.workflow }}\` - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|로그 보기>\"}" \
          $SLACK_WEBHOOK_URL
