name: Generate and Upload Video

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client elevenlabs ffmpeg-python

      - name: Prepare credentials
        run: |
          echo "${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}" > credentials.json
          echo "${{ secrets.GOOGLE_TOKEN_JSON_BASE64 }}" | base64 --decode > token.json

      - name: Run upload script
        run: |
          python scripts/upload_video.py \
            --file "output/video.mp4" \
            --title "자동 생성된 영상 제목" \
            --description "자동 생성된 영상 설명" \
            --category "22" \
            --keywords "자동화,유튜브" \
            --privacy_status "public"
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
